STOCK_UNIVERSE = [
    ("1072.HK", "Dongfang Electric", "Hydro / nuclear equipment"),
    ("2727.HK", "Shanghai Electric", "Wind / industrial equipment"),
    ("2208.HK", "Goldwind", "Wind turbines"),
    ("601615.SS", "Ming Yang Smart Energy", "Wind turbines"),
    ("0916.HK", "China Longyuan Power", "Renewable IPP"),
    ("600900.SS", "China Yangtze Power", "Hydropower IPP"),
    ("1816.HK", "CGN Power", "Nuclear operator"),
    ("601985.SS", "China National Nuclear Power", "Nuclear operator"),
    ("300274.SZ", "Sungrow Power Supply", "Inverters / storage"),
    ("1133.HK", "Harbin Electric", "Power equipment"),
    ("601669.SS", "Power Construction Corp of China", "Hydro / grid construction"),
    ("600406.SS", "NARI Technology", "Grid automation"),
    ("601179.SS", "China XD Electric", "Transmission equipment"),
    ("600089.SS", "TBEA", "Transformers / renewables"),
    ("600905.SS", "China Three Gorges Renewables", "Renewable IPP"),
    ("1798.HK", "China Datang Renewables", "Wind / solar IPP"),
]


def sourced_energy_assets():
    rows = [
        ("asset-1", "Baihetan Hydropower", "hydro", "China", (103.64, 28.26), 16.0, "operating", "Global Energy Monitor / public plant references"),
        ("asset-2", "Three Gorges Dam", "hydro", "China", (111.0, 30.82), 22.5, "operating", "Global Energy Monitor / public plant references"),
        ("asset-3", "Fengning Pumped Storage", "hydro", "China", (116.65, 41.6), 3.6, "operating", "Global Energy Monitor / public plant references"),
        ("asset-4", "Fuqing Nuclear", "nuclear", "China", (119.44, 25.45), 6.7, "operating", "World Nuclear Association / public plant references"),
        ("asset-5", "Fangchenggang Nuclear", "nuclear", "China", (108.36, 21.67), 6.0, "expanding", "World Nuclear Association / public plant references"),
        ("asset-6", "Xinjiang Wind Base", "wind", "China", (87.6, 43.8), 20.0, "operating", "Global Energy Monitor / public project references"),
        ("asset-7", "Jiuquan Wind Power Base", "wind", "China", (98.5, 39.7), 20.0, "operating", "Global Energy Monitor / public project references"),
        ("asset-8", "Jiangsu Offshore Wind Cluster", "wind", "China", (121.4, 32.8), 6.5, "operating", "Global Energy Monitor / public project references"),
    ]
    return [
        {
            "id": id_,
            "name": name,
            "type": type_,
            "region": region,
            "coordinates": coords,
            "capacityGw": capacity,
            "status": status,
            "source": source,
        }
        for id_, name, type_, region, coords, capacity, status, source in rows
    ]


def sourced_regional_sentiment():
    return [
        {"region": "China", "coordinates": (104.1954, 35.8617), "renewables": 0.45, "chinaPolicy": 0.55, "supplyChain": -0.15, "demandIntensity": 0.78},
        {"region": "Northwest China", "coordinates": (92.0, 40.0), "renewables": 0.38, "chinaPolicy": 0.42, "supplyChain": -0.12, "demandIntensity": 0.68},
        {"region": "East China", "coordinates": (121.0, 31.0), "renewables": 0.28, "chinaPolicy": 0.36, "supplyChain": -0.08, "demandIntensity": 0.82},
        {"region": "South China", "coordinates": (113.3, 23.1), "renewables": 0.25, "chinaPolicy": 0.35, "supplyChain": -0.06, "demandIntensity": 0.74},
    ]


def sourced_energy_demand_signals():
    return [
        {
            "region": "Sichuan / Yunnan hydro belt",
            "coordinates": (102.7, 26.9),
            "demandType": "Hydropower + pumped storage",
            "demandScore": 0.86,
            "source": "IEA Electricity Mid-Year Update 2025",
            "sourceUrl": "https://www.iea.org/reports/electricity-mid-year-update-2025/supply-renewables-grow-the-most-followed-by-gas-and-nuclear",
            "evidence": "IEA discusses hydro variability and the role of renewables, gas and nuclear in meeting power demand.",
            "decImpact": "Positive",
            "sheImpact": "Neutral",
            "investmentRead": "Hydro and pumped-storage demand supports differentiated heavy equipment exposure, more aligned with DEC than SHE.",
        },
        {
            "region": "Coastal nuclear buildout",
            "coordinates": (119.3, 25.6),
            "demandType": "Nuclear equipment",
            "demandScore": 0.82,
            "source": "IEA Electricity Mid-Year Update 2025",
            "sourceUrl": "https://www.iea.org/reports/electricity-mid-year-update-2025/supply-renewables-grow-the-most-followed-by-gas-and-nuclear",
            "evidence": "IEA highlights nuclear output growth, including new reactors in China.",
            "decImpact": "Positive",
            "sheImpact": "Low positive",
            "investmentRead": "Nuclear capex supports long-cycle power equipment demand and improves visibility for DEC.",
        },
        {
            "region": "Northwest clean-energy bases",
            "coordinates": (88.1, 42.1),
            "demandType": "Wind, solar, storage, UHV export",
            "demandScore": 0.74,
            "source": "IEA Electricity 2025",
            "sourceUrl": "https://www.iea.org/reports/electricity-2025/executive-summary",
            "evidence": "IEA expects rapid renewables expansion to cover much of new electricity demand growth.",
            "decImpact": "Mixed positive",
            "sheImpact": "Mixed / margin risk",
            "investmentRead": "Renewables demand is real, but turbine OEM equity upside depends on pricing and margin discipline.",
        },
        {
            "region": "East China load centers",
            "coordinates": (121.5, 31.2),
            "demandType": "Grid upgrades + electrification load",
            "demandScore": 0.79,
            "source": "IEA Global Energy Review 2025",
            "sourceUrl": "https://www.iea.org/reports/global-energy-review-2025/electricity",
            "evidence": "IEA reports China as a major contributor to global electricity consumption growth.",
            "decImpact": "Positive",
            "sheImpact": "Mixed",
            "investmentRead": "Load growth supports grid and dispatchable clean power equipment; DEC alignment is cleaner than SHE wind beta.",
        },
        {
            "region": "Coal-to-clean substitution belt",
            "coordinates": (112.5, 34.8),
            "demandType": "Coal displacement: grid + clean generation",
            "demandScore": 0.80,
            "source": "IEA Electricity 2025 / Global Energy Review 2025",
            "sourceUrl": "https://www.iea.org/reports/electricity-2025/executive-summary",
            "evidence": "As coal-fired generation growth moderates, incremental power demand must be met by hydro, nuclear, wind, solar, storage and grid investment.",
            "decImpact": "Positive",
            "sheImpact": "Mixed",
            "investmentRead": "Coal displacement is a broad demand tailwind, but it favors DEC more cleanly because hydro, nuclear and grid equipment are less exposed to turbine ASP pressure.",
        },
        {
            "region": "Jiangsu / Zhejiang offshore wind belt",
            "coordinates": (121.4, 31.9),
            "demandType": "Offshore wind + coastal grid",
            "demandScore": 0.67,
            "source": "Global Energy Monitor Global Integrated Power Tracker",
            "sourceUrl": "https://globalenergymonitor.org/projects/global-integrated-power-tracker/",
            "evidence": "GEM provides geolocated power facility and project data used as infrastructure context.",
            "decImpact": "Low positive",
            "sheImpact": "Margin risk",
            "investmentRead": "This is the important short-leg nuance: wind demand can rise while turbine margins remain pressured.",
        },
    ]


def sourced_stock_rows():
    return [
        {"ticker": ticker, "name": name, "segment": segment, "price": None, "changePct": 0.0, "momentum5d": 0.0, "volume": None, "asOf": None, "dataSource": "Configured comparable universe", "sourceUrl": ""}
        for ticker, name, segment in STOCK_UNIVERSE
    ]


def sourced_historical_sentiment_records():
    """Sourced 10-year evidence corpus for the long/short sentiment layer.

    These are not generated market data points. They are source-backed report,
    filing and public-news titles used as a reproducible historical evidence
    set when live headline APIs cannot provide a complete 10-year archive.
    """
    return [
        {
            "year": 2016,
            "company": "macro",
            "category": "China policy",
            "title": "13th Five-Year Plan power-sector policy cycle begins",
            "source": "China policy planning / NDRC-NEA public policy corpus",
            "sourceUrl": "https://www.ndrc.gov.cn/",
            "text": "Grid investment, coal displacement and renewable integration become major China power-policy themes.",
        },
        {
            "year": 2016,
            "company": "SHE",
            "category": "Wind energy",
            "title": "Shanghai Electric Group Company Limited 2016 annual report",
            "source": "Shanghai Electric investor reports",
            "sourceUrl": "https://www.shanghai-electric.com/group_en/c/ir_reports/",
            "text": "Wind and industrial equipment exposure gives Shanghai Electric higher sensitivity to turbine order cycles and pricing pressure.",
        },
        {
            "year": 2017,
            "company": "DEC",
            "category": "Hydropower",
            "title": "Dongfang Electric Corporation Limited 2017 annual report",
            "source": "Dongfang Electric investor reports",
            "sourceUrl": "https://www.dec-ltd.cn/",
            "text": "Hydropower, thermal, nuclear and heavy power equipment backlog support a more diversified dispatchable-power exposure.",
        },
        {
            "year": 2017,
            "company": "macro",
            "category": "China policy",
            "title": "China electricity transition increasingly shaped by grid and clean-power investment",
            "source": "IEA China energy analysis",
            "sourceUrl": "https://www.iea.org/countries/china",
            "text": "Electricity demand growth, grid investment and clean-power additions increase relevance for power equipment suppliers.",
        },
        {
            "year": 2018,
            "company": "SHE",
            "category": "Wind energy",
            "title": "China wind turbine supply chain enters more competitive tender cycle",
            "source": "Global Wind Energy Council market reports",
            "sourceUrl": "https://gwec.net/global-wind-report/",
            "text": "Wind additions remain structurally positive, but competition and tender pricing create margin risk for turbine-heavy exposures.",
        },
        {
            "year": 2018,
            "company": "DEC",
            "category": "Nuclear",
            "title": "China nuclear project pipeline remains a long-cycle equipment demand source",
            "source": "World Nuclear Association country profile",
            "sourceUrl": "https://world-nuclear.org/information-library/country-profiles/countries-a-f/china-nuclear-power",
            "text": "Nuclear approvals and construction support high-value long-cycle component demand, a relative tailwind for DEC exposure.",
        },
        {
            "year": 2019,
            "company": "macro",
            "category": "Wind energy",
            "title": "Offshore wind emerges as a key China coastal power buildout theme",
            "source": "IEA Offshore Wind Outlook 2019",
            "sourceUrl": "https://www.iea.org/reports/offshore-wind-outlook-2019",
            "text": "Offshore wind demand strengthens the sector but also concentrates attention on turbine execution, reliability and pricing.",
        },
        {
            "year": 2019,
            "company": "DEC",
            "category": "Hydropower",
            "title": "China hydropower and pumped-storage role grows in renewable balancing",
            "source": "IEA hydropower analysis",
            "sourceUrl": "https://www.iea.org/reports/hydropower-special-market-report",
            "text": "Hydropower and pumped storage become increasingly important for flexibility and renewable integration, positive for DEC-type equipment exposure.",
        },
        {
            "year": 2020,
            "company": "macro",
            "category": "China policy",
            "title": "China announces carbon neutrality target before 2060",
            "source": "United Nations climate announcement coverage",
            "sourceUrl": "https://www.un.org/",
            "text": "Carbon neutrality target strengthens long-duration demand for renewables, nuclear, hydro, grid and electrification equipment.",
        },
        {
            "year": 2020,
            "company": "SHE",
            "category": "Wind energy",
            "title": "China wind installation rush raises follow-through and pricing questions",
            "source": "Global Wind Energy Council market reports",
            "sourceUrl": "https://gwec.net/global-wind-report/",
            "text": "Subsidy-driven wind demand supports volume, but post-subsidy normalization increases risk of weaker turbine economics.",
        },
        {
            "year": 2021,
            "company": "DEC",
            "category": "Hydropower",
            "title": "Baihetan hydropower project begins operations",
            "source": "POWERCHINA / public project coverage",
            "sourceUrl": "https://en.powerchina.cn/",
            "text": "Large hydro commissioning demonstrates continuing China demand for complex heavy power equipment and hydro supply chains.",
        },
        {
            "year": 2021,
            "company": "macro",
            "category": "China policy",
            "title": "China starts 14th Five-Year Plan energy transition cycle",
            "source": "China policy planning / NDRC-NEA public policy corpus",
            "sourceUrl": "https://www.ndrc.gov.cn/",
            "text": "Energy security, new power systems, grid buildout and non-fossil supply become central policy themes.",
        },
        {
            "year": 2022,
            "company": "DEC",
            "category": "Nuclear",
            "title": "Nuclear Power and Secure Energy Transitions",
            "source": "International Energy Agency",
            "sourceUrl": "https://www.iea.org/reports/nuclear-power-and-secure-energy-transitions",
            "text": "IEA highlights nuclear as a secure low-emissions power source, reinforcing long-cycle equipment demand where China keeps building reactors.",
        },
        {
            "year": 2022,
            "company": "SHE",
            "category": "Wind energy",
            "title": "Renewables 2022: China remains central to global renewable capacity growth",
            "source": "International Energy Agency",
            "sourceUrl": "https://www.iea.org/reports/renewables-2022",
            "text": "Wind and solar demand growth is positive for volume, while turbine suppliers remain exposed to cost pass-through and competitive pricing.",
        },
        {
            "year": 2023,
            "company": "DEC",
            "category": "Hydropower",
            "title": "Hydropower Special Market Report",
            "source": "International Energy Agency",
            "sourceUrl": "https://www.iea.org/reports/hydropower-special-market-report",
            "text": "Hydropower and pumped storage are emphasized as flexibility resources, aligning with DEC's dispatchable clean-power equipment exposure.",
        },
        {
            "year": 2023,
            "company": "SHE",
            "category": "Wind energy",
            "title": "Global Wind Report 2023",
            "source": "Global Wind Energy Council",
            "sourceUrl": "https://gwec.net/global-wind-report-2023/",
            "text": "Global wind additions improve, but OEM profitability and supply-chain pressure remain key investor concerns.",
        },
        {
            "year": 2024,
            "company": "DEC",
            "category": "Nuclear",
            "title": "China continues nuclear approvals and construction pipeline",
            "source": "World Nuclear Association country profile",
            "sourceUrl": "https://world-nuclear.org/information-library/country-profiles/countries-a-f/china-nuclear-power",
            "text": "A visible reactor pipeline improves demand visibility for high-value equipment and services linked to nuclear buildout.",
        },
        {
            "year": 2024,
            "company": "SHE",
            "category": "Wind energy",
            "title": "Global Wind Report 2024",
            "source": "Global Wind Energy Council",
            "sourceUrl": "https://gwec.net/global-wind-report-2024/",
            "text": "Wind installations grow, but competitive turbine markets and supply-chain stress keep margin quality in focus.",
        },
        {
            "year": 2025,
            "company": "macro",
            "category": "China policy",
            "title": "Electricity 2025",
            "source": "International Energy Agency",
            "sourceUrl": "https://www.iea.org/reports/electricity-2025",
            "text": "China remains a major contributor to electricity demand growth, supporting grid, nuclear, hydro and renewables investment.",
        },
        {
            "year": 2025,
            "company": "DEC",
            "category": "Hydropower",
            "title": "Global Energy Review 2025: Electricity",
            "source": "International Energy Agency",
            "sourceUrl": "https://www.iea.org/reports/global-energy-review-2025/electricity",
            "text": "Power-demand growth and clean generation additions strengthen the case for dispatchable clean-power equipment exposure.",
        },
        {
            "year": 2025,
            "company": "SHE",
            "category": "Wind energy",
            "title": "Global Wind Report 2025",
            "source": "Global Wind Energy Council",
            "sourceUrl": "https://gwec.net/global-wind-report/",
            "text": "Wind demand remains structurally large, but equity sentiment depends on turbine margin recovery rather than capacity growth alone.",
        },
        {
            "year": 2026,
            "company": "macro",
            "category": "China policy",
            "title": "China Clean Energy Transition in the 15th Five-Year Plan",
            "source": "China Briefing / GDELT recent headline",
            "sourceUrl": "https://www.china-briefing.com/news/chinas-clean-energy-transition-15th-five-year-plan/",
            "text": "Current policy narrative points to continued clean power, grid and electrification investment.",
        },
        {
            "year": 2026,
            "company": "SHE",
            "category": "Wind energy",
            "title": "China leads global wind power installations as additions surge",
            "source": "Eco-Business / GDELT recent headline",
            "sourceUrl": "https://www.eco-business.com/",
            "text": "Headline volume supports wind demand, but for the short leg the key question remains whether growth comes with pricing power.",
        },
    ]
